# Dosya Yolu: /tools/docker/Dockerfile.compat
# Amac: Resmi Dockerfile bulunmayan eski OFBiz release paketleri icin runtime ve demo image'lari olusturur
# Config - Dockerfile
# Version: 2.0.1
# Aciklama: Legacy wrapper checksum uyumlulugu ve Java major build arg ile runtime/demo image'lari olusturur
#
# Bagimli Oldugu Katman: Config | Tool

ARG JAVA_MAJOR=17

FROM eclipse-temurin:${JAVA_MAJOR}-jdk AS base

WORKDIR /ofbiz

COPY . /ofbiz

RUN chmod +x gradlew \
    && if [ -f gradle/init-gradle-wrapper.sh ]; then \
        sed -i 's/shasum/sha1sum/g' gradle/init-gradle-wrapper.sh; \
        bash gradle/init-gradle-wrapper.sh; \
    fi

EXPOSE 8443 8009 5005

FROM base AS runtime

CMD ["./gradlew", "ofbiz"]

FROM base AS demo

RUN ./gradlew --no-daemon loadAll

CMD ["./gradlew", "ofbiz"]
